services:
  mysql:
    image: mysql:8.0
    container_name: keycloak_mysql
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306" # Porta do MySQL exposta no host como 3307
    volumes:
      - mysql_data:/var/lib/mysql # Volume para persistência de dados
    networks:
      - keycloak_network # Rede compartilhada com o Keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak_server
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak_mysql
      KC_DB_URL_PORT: 3306
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KC_ADMIN: admin
      KC_ADMIN_PASSWORD: admin
    command: >
      start-dev
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - keycloak_network


volumes:
  mysql_data: # Volume para persistência dos dados do MySQL

networks:
  keycloak_network:
    driver: bridge # Rede do tipo bridge para os contêineres
